# azure-pipelines-simple.yml
trigger:
  branches:
    include:
    - main

variables:
  azureSubscription: 'novya-serviceconnection'
  appName: 'backend-n'
  nodeVersion: '18.x'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: |
    echo "Installing dependencies..."
    npm install --legacy-peer-deps
    echo "✅ Dependencies installed!"
  displayName: 'Install dependencies'

- script: |
    echo "Building application..."
    npm run build
    echo "✅ Build completed!"
  displayName: 'Build application'

- script: |
    echo "Running tests..."
    npm test -- --watchAll=false --passWithNoTests
    echo "✅ Tests completed!"
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/build'
    artifact: 'build'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'